steps:
# Uses the docker build step to build an image called cloud-run-pubsub-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME', '.']

# cloud-run-pubsub-service is pushed to Container Registry
images:
- 'gcr.io/$PROJECT_ID/$_IMAGE_NAME'